name: Deploy
on:
  push:
    branches:
      - main
      - web-remix

jobs:
  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/api
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  deploy-web-remix:
    name: Deploy Web Remix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config ./apps/web-remix/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_WEB_DEPLOY_TOKEN }}
