name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pnpm i

      # TODO: add a build step here
      - name: Build Astro
        run: pnpm build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 'npbee-waveformr'
          entrypoint: 'server/entry.mjs'
          root: dist
